version: '3.7'

services:

  database:
    image: mysql
    environment:
      MYSQL_DATABASE: innoscripta
      MYSQL_USER: innoscripta
      MYSQL_PASSWORD: innoscripta
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - 3306:3306
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
    - app

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    # environment:
    #   DB_HOST: database
    #   DB_PORT: 3306
    #   DB_DATABASE: innoscripta
    #   DB_USERNAME: innoscripta
    #   DB_PASSWORD: innoscripta
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - database
    networks:
      - app
  
  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge